### ISSUE TITLE
Content Security Policy

### ISSUE THREAD

**Issue by rudolphh** [freeCodeCamp/boilerplate-project-stockchecker#1]
Maybe this should be left open to campers completing the project, but I was thinking about how it's a little too easy of a user story to simply add 'self' for the directives in the CSP.  Maybe we could add a few other user stories to give a more thorough type of learning? I know it helped me understand the Content Security Policy better, as well as the various console errors I was seeing. 

For example, simply adding 'self' as values for directives brings about problems with the current setup.  JQuery, for one, does not load.  Inline scripts in index.html do not load, and have to be put in their own file and referenced.  Inline styles do not load as well, and campers could make good use of the empty style.css file in the public folder.

**Comment by moT01** [comment]
Please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
