### ISSUE TITLE
Project Solution

### ISSUE THREAD

**Issue by rudolphh** [freeCodeCamp/boilerplate-project-stockchecker#2]
First off thank you so much for the boilerplate for the project.  

As for the solution to test a user's own solution, there is an issue that has to do with the asynchronous behavior of the code. 

Perhaps adding a section for asynchronous code would be beneficial.  While a campers' solution should incorporate some of those concepts, the example solution, which one might test their own code against, seems to assume synchronous code.  

For example, the relative likes of a stock are not consistent.  A simple callback would work, as FCC hasn't yet introduced promises or generators. 

To test this, simply put in two stocks in a query and refresh over and over.  You will eventually get different results based on when particular responses (to requests) were received.

**Comment by moT01** [comment]
Please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
